[package]
name = "gitbase"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.9"
git2 = "0.20.4"
log = "0.4.29"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.149"
thiserror = "2.0.18"
